//! Localized chrome labels: one [`Label`] per user-visible string.

// Rust guideline compliant 2026-10-07

use crate::locale::Locale;

/// A user-visible chrome string.
///
/// Each variant resolves through [`Label::t`]. The per-locale matches are exhaustive, so adding
/// a variant is a compile error until every locale provides it. Product names, key glyphs,
/// URLs, and dynamic data stay literals at their paint sites instead of becoming labels.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Label {
    // Sidebar.
    Spaces,
    NewSpace,
    // Gear menu.
    Settings,
    Shortcuts,
    CheckForUpdates,
    Documentation,
    AboutVivida,
    // Workspace and tab context menu.
    Rename,
    Reset,
    ResetTerminal,
    RestartTerminal,
    Cancel,
    // Rename editor.
    RenameSpace,
    RenameTab,
    // Shortcuts and About panels.
    ShortcutsHeader,
    ShortcutsWindowTitle,
    ProductName,
    SectionTerminal,
    SectionSearch,
    Version,
    // Shortcut rows: Vivida.
    NewTab,
    SplitHorizontal,
    SplitVertical,
    CloseFocusedPane,
    NewSpaceShortcut,
    CloseSpace,
    CycleSidebar,
    NextTab,
    PreviousTab,
    SwitchToSpace,
    RecoverTerminal,
    // Shortcut rows: terminal.
    CopySelection,
    Paste,
    PastePrimarySelection,
    CommandPalette,
    SearchForward,
    SearchBackward,
    ClearScrollback,
    ResetFontSize,
    ChangeFontSize,
    ToggleFullscreen,
    OpenLinkOnScreen,
    ScrollOnePage,
    ScrollToEnd,
    // Shortcut rows: search mode.
    ConfirmMatch,
    CancelSearch,
    NextOrPreviousMatch,
    ClearQuery,
    SearchHistory,
}

impl Label {
    /// Every label, in enum order.
    pub const ALL: &[Self] = &[
        Self::Spaces,
        Self::NewSpace,
        Self::Settings,
        Self::Shortcuts,
        Self::CheckForUpdates,
        Self::Documentation,
        Self::AboutVivida,
        Self::Rename,
        Self::Reset,
        Self::ResetTerminal,
        Self::RestartTerminal,
        Self::Cancel,
        Self::RenameSpace,
        Self::RenameTab,
        Self::ShortcutsHeader,
        Self::ShortcutsWindowTitle,
        Self::ProductName,
        Self::SectionTerminal,
        Self::SectionSearch,
        Self::Version,
        Self::NewTab,
        Self::SplitHorizontal,
        Self::SplitVertical,
        Self::CloseFocusedPane,
        Self::NewSpaceShortcut,
        Self::CloseSpace,
        Self::CycleSidebar,
        Self::NextTab,
        Self::PreviousTab,
        Self::SwitchToSpace,
        Self::RecoverTerminal,
        Self::CopySelection,
        Self::Paste,
        Self::PastePrimarySelection,
        Self::CommandPalette,
        Self::SearchForward,
        Self::SearchBackward,
        Self::ClearScrollback,
        Self::ResetFontSize,
        Self::ChangeFontSize,
        Self::ToggleFullscreen,
        Self::OpenLinkOnScreen,
        Self::ScrollOnePage,
        Self::ScrollToEnd,
        Self::ConfirmMatch,
        Self::CancelSearch,
        Self::NextOrPreviousMatch,
        Self::ClearQuery,
        Self::SearchHistory,
    ];

    /// Resolve this label in `locale`.
    pub fn t(self, locale: Locale) -> &'static str {
        match locale {
            Locale::En => match self {
                Self::Spaces => "Spaces",
                Self::NewSpace => "+ New Space",
                Self::Settings => "Settings",
                Self::Shortcuts => "Shortcuts",
                Self::CheckForUpdates => "Check for Updates…",
                Self::Documentation => "Documentation",
                Self::AboutVivida => "About Vivida",
                Self::Rename => "Rename",
                Self::Reset => "Reset",
                Self::ResetTerminal => "Reset Terminal",
                Self::RestartTerminal => "Restart Terminal",
                Self::Cancel => "Cancel",
                Self::RenameSpace => "Rename Space",
                Self::RenameTab => "Rename Tab",
                Self::ShortcutsHeader => "Keyboard Shortcuts",
                Self::ShortcutsWindowTitle => "Vivida shortcuts",
                Self::ProductName => "Vivida",
                Self::SectionTerminal => "Terminal",
                Self::SectionSearch => "While searching",
                Self::Version => "Version",
                Self::NewTab => "New tab",
                Self::SplitHorizontal => "Split the pane left and right",
                Self::SplitVertical => "Split the pane top and bottom",
                Self::CloseFocusedPane => "Close the focused pane",
                Self::NewSpaceShortcut => "New space",
                Self::CloseSpace => "Close the space",
                Self::CycleSidebar => "Expand, shrink, or hide the sidebar",
                Self::NextTab => "Next tab",
                Self::PreviousTab => "Previous tab",
                Self::SwitchToSpace => "Switch to space 1 through 9",
                Self::RecoverTerminal => "Recover a stuck terminal",
                Self::CopySelection => "Copy the selection",
                Self::Paste => "Paste",
                Self::PastePrimarySelection => "Paste the primary selection",
                Self::CommandPalette => "Command palette",
                Self::SearchForward => "Search forward",
                Self::SearchBackward => "Search backward",
                Self::ClearScrollback => "Clear the scrollback",
                Self::ResetFontSize => "Reset the font size",
                Self::ChangeFontSize => "Increase or decrease the font size",
                Self::ToggleFullscreen => "Toggle fullscreen",
                Self::OpenLinkOnScreen => "Open a link shown on screen",
                Self::ScrollOnePage => "Scroll one page",
                Self::ScrollToEnd => "Scroll to the top or bottom",
                Self::ConfirmMatch => "Confirm the match",
                Self::CancelSearch => "Cancel the search",
                Self::NextOrPreviousMatch => "Next or previous match",
                Self::ClearQuery => "Clear the query",
                Self::SearchHistory => "Previous or next search in history",
            },
            Locale::ZhHant => match self {
                Self::Spaces => "空間",
                Self::NewSpace => "+ 新增空間",
                Self::Settings => "設定",
                Self::Shortcuts => "快速鍵",
                Self::CheckForUpdates => "檢查更新…",
                Self::Documentation => "文件",
                Self::AboutVivida => "關於 Vivida",
                Self::Rename => "重新命名",
                Self::Reset => "重設",
                Self::ResetTerminal => "重設終端機",
                Self::RestartTerminal => "重新啟動終端機",
                Self::Cancel => "取消",
                Self::RenameSpace => "重新命名空間",
                Self::RenameTab => "重新命名分頁",
                Self::ShortcutsHeader => "鍵盤快速鍵",
                Self::ShortcutsWindowTitle => "Vivida 快速鍵",
                Self::ProductName => "Vivida",
                Self::SectionTerminal => "終端機",
                Self::SectionSearch => "搜尋時",
                Self::Version => "版本",
                Self::NewTab => "新增分頁",
                Self::SplitHorizontal => "左右分割窗格",
                Self::SplitVertical => "上下分割窗格",
                Self::CloseFocusedPane => "關閉焦點窗格",
                Self::NewSpaceShortcut => "新增空間",
                Self::CloseSpace => "關閉空間",
                Self::CycleSidebar => "展開、縮小或隱藏側欄",
                Self::NextTab => "下一個分頁",
                Self::PreviousTab => "上一個分頁",
                Self::SwitchToSpace => "切換到空間 1 至 9",
                Self::RecoverTerminal => "修復卡住的終端機",
                Self::CopySelection => "複製選取內容",
                Self::Paste => "貼上",
                Self::PastePrimarySelection => "貼上主要選取內容",
                Self::CommandPalette => "命令面板",
                Self::SearchForward => "向前搜尋",
                Self::SearchBackward => "向後搜尋",
                Self::ClearScrollback => "清除捲動緩衝區",
                Self::ResetFontSize => "重設字型大小",
                Self::ChangeFontSize => "增大或縮小字型大小",
                Self::ToggleFullscreen => "切換全螢幕",
                Self::OpenLinkOnScreen => "開啟畫面上的連結",
                Self::ScrollOnePage => "捲動一頁",
                Self::ScrollToEnd => "捲動到頂端或底部",
                Self::ConfirmMatch => "確認相符項目",
                Self::CancelSearch => "取消搜尋",
                Self::NextOrPreviousMatch => "下一個或上一個相符項目",
                Self::ClearQuery => "清除搜尋字詞",
                Self::SearchHistory => "歷史中的上一個或下一個搜尋",
            },
            Locale::ZhHans => match self {
                Self::Spaces => "空间",
                Self::NewSpace => "+ 新建空间",
                Self::Settings => "设置",
                Self::Shortcuts => "快捷键",
                Self::CheckForUpdates => "检查更新…",
                Self::Documentation => "文档",
                Self::AboutVivida => "关于 Vivida",
                Self::Rename => "重命名",
                Self::Reset => "重置",
                Self::ResetTerminal => "重置终端",
                Self::RestartTerminal => "重启终端",
                Self::Cancel => "取消",
                Self::RenameSpace => "重命名空间",
                Self::RenameTab => "重命名标签页",
                Self::ShortcutsHeader => "键盘快捷键",
                Self::ShortcutsWindowTitle => "Vivida 快捷键",
                Self::ProductName => "Vivida",
                Self::SectionTerminal => "终端",
                Self::SectionSearch => "搜索时",
                Self::Version => "版本",
                Self::NewTab => "新建标签页",
                Self::SplitHorizontal => "左右拆分窗格",
                Self::SplitVertical => "上下拆分窗格",
                Self::CloseFocusedPane => "关闭焦点窗格",
                Self::NewSpaceShortcut => "新建空间",
                Self::CloseSpace => "关闭空间",
                Self::CycleSidebar => "展开、缩小或隐藏侧栏",
                Self::NextTab => "下一个标签页",
                Self::PreviousTab => "上一个标签页",
                Self::SwitchToSpace => "切换到空间 1 至 9",
                Self::RecoverTerminal => "修复卡住的终端",
                Self::CopySelection => "复制所选内容",
                Self::Paste => "粘贴",
                Self::PastePrimarySelection => "粘贴主要选区",
                Self::CommandPalette => "命令面板",
                Self::SearchForward => "向前搜索",
                Self::SearchBackward => "向后搜索",
                Self::ClearScrollback => "清除回滚缓冲区",
                Self::ResetFontSize => "重置字体大小",
                Self::ChangeFontSize => "增大或缩小字体大小",
                Self::ToggleFullscreen => "切换全屏",
                Self::OpenLinkOnScreen => "打开屏幕上的链接",
                Self::ScrollOnePage => "滚动一页",
                Self::ScrollToEnd => "滚动到顶部或底部",
                Self::ConfirmMatch => "确认匹配项",
                Self::CancelSearch => "取消搜索",
                Self::NextOrPreviousMatch => "下一个或上一个匹配项",
                Self::ClearQuery => "清除搜索词",
                Self::SearchHistory => "历史中的上一个或下一个搜索",
            },
            Locale::Ja => match self {
                Self::Spaces => "スペース",
                Self::NewSpace => "+ 新規スペース",
                Self::Settings => "設定",
                Self::Shortcuts => "ショートカット",
                Self::CheckForUpdates => "更新を確認…",
                Self::Documentation => "ドキュメント",
                Self::AboutVivida => "Vivida について",
                Self::Rename => "名前を変更",
                Self::Reset => "リセット",
                Self::ResetTerminal => "端末をリセット",
                Self::RestartTerminal => "端末を再起動",
                Self::Cancel => "キャンセル",
                Self::RenameSpace => "スペース名を変更",
                Self::RenameTab => "タブ名を変更",
                Self::ShortcutsHeader => "キーボードショートカット",
                Self::ShortcutsWindowTitle => "Vivida ショートカット",
                Self::ProductName => "Vivida",
                Self::SectionTerminal => "端末",
                Self::SectionSearch => "検索中",
                Self::Version => "バージョン",
                Self::NewTab => "新規タブ",
                Self::SplitHorizontal => "ペインを左右に分割",
                Self::SplitVertical => "ペインを上下に分割",
                Self::CloseFocusedPane => "フォーカスされたペインを閉じる",
                Self::NewSpaceShortcut => "新規スペース",
                Self::CloseSpace => "スペースを閉じる",
                Self::CycleSidebar => "サイドバーの展開・縮小・非表示",
                Self::NextTab => "次のタブ",
                Self::PreviousTab => "前のタブ",
                Self::SwitchToSpace => "スペース 1〜9 に切り替え",
                Self::RecoverTerminal => "フリーズした端末を復旧",
                Self::CopySelection => "選択範囲をコピー",
                Self::Paste => "貼り付け",
                Self::PastePrimarySelection => "プライマリ選択を貼り付け",
                Self::CommandPalette => "コマンドパレット",
                Self::SearchForward => "前方検索",
                Self::SearchBackward => "後方検索",
                Self::ClearScrollback => "スクロールバックをクリア",
                Self::ResetFontSize => "フォントサイズをリセット",
                Self::ChangeFontSize => "フォントサイズの拡大・縮小",
                Self::ToggleFullscreen => "フルスクリーン切り替え",
                Self::OpenLinkOnScreen => "画面上のリンクを開く",
                Self::ScrollOnePage => "1 ページスクロール",
                Self::ScrollToEnd => "先頭または末尾へスクロール",
                Self::ConfirmMatch => "マッチを確定",
                Self::CancelSearch => "検索をキャンセル",
                Self::NextOrPreviousMatch => "次または前のマッチ",
                Self::ClearQuery => "クエリをクリア",
                Self::SearchHistory => "履歴の前または次の検索",
            },
        }
    }
}

// Referenced so variants used only by another platform's shortcut tables stay live on every
// target, and so `ALL` — consumed by tests alone — is used by plain builds too.
const _: usize = Label::ALL.len();

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_label_resolves_in_every_locale() {
        for label in Label::ALL {
            for locale in Locale::ALL {
                assert!(
                    !label.t(*locale).is_empty(),
                    "{label:?} is empty in {locale:?}"
                );
            }
        }
    }

    #[test]
    fn invariant_labels_hold_in_every_locale() {
        for locale in Locale::ALL {
            // The compact sidebar centers a bare "+", so the expanded footer keeps the prefix.
            assert!(Label::NewSpace.t(*locale).starts_with('+'));
            assert_eq!(Label::ProductName.t(*locale), "Vivida");
        }
    }
}
